import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const config = JSON.parse(read('vercel.json'));
const pkg = JSON.parse(read('package.json'));
test('Vercel usa Other e saída estática',()=>{assert.equal(config.framework,null);assert.equal(config.outputDirectory,'public');assert.equal(config.buildCommand,'npm run build');assert.equal(pkg.engines.node,'>=22.16.0 <23');assert.equal(config.builds,undefined);});
test('API Node preservada e rota Python explícita antes do catch-all',()=>{assert.deepEqual(Object.keys(config.functions),['api/index.ts','api/reports.py','api/simples.py']);assert.deepEqual(config.rewrites,[{source:'/api/reports',destination:'/api/reports'},{source:'/api/simples',destination:'/api/simples'},{source:'/api/:path*',destination:'/api'}]);assert.match(read('api/index.ts'),/from ['"]\.\.\/src\/server\.ts['"]/);assert.doesNotMatch(read('api/index.ts'),/public\/|document\.|window\./);assert.match(read('api/reports.py'),/authenticate/);assert.match(read('api/simples.py'),/authenticate/);const pyproject=read('pyproject.toml');assert.match(pyproject,/opencv-python-headless==5\.0\.0\.93/);assert.match(pyproject,/exclude-dependencies\s*=\s*\["opencv-python"\]/);assert.equal(existsSync(new URL('../requirements.txt',import.meta.url)),false);assert.match(read('public/reports.html'),/reports-ui\.js/);});
test('HTML novo e legado são scripts de navegador; favicon estático',()=>{assert.match(read('public/index.html'),/<script type="module" src="\/lookup-ui\.js"><\/script>/);assert.match(read('public/legacy.html'),/<script type="module" src="\/app\.js"><\/script>/);assert.match(read('public/index.html'),/href="\/favicon\.svg"/);assert.deepEqual(config.redirects,[{source:'/favicon.ico',destination:'/favicon.svg',permanent:false}]);});
test('Headers protegem HTML e API não é cacheada',()=>{const h=new Map(config.headers.find(v=>v.source==='/(.*)').headers.map(v=>[v.key,v.value]));assert.equal(h.get('X-Maximum-Deployment'),'static-api-v1');assert.match(h.get('Content-Security-Policy'),/script-src 'self'/);assert.match(h.get('Content-Security-Policy'),/frame-ancestors 'none'/);assert.ok(config.headers.find(v=>v.source==='/api/:path*').headers.some(v=>v.key==='Cache-Control'&&v.value==='no-store'));});
test('Versão e diagnóstico sem dependências Google',()=>{assert.ok(read('src/domain.ts').includes(`VERSION = '${pkg.version}'`));assert.equal(pkg.scripts['test:deployment'],'node --test tests/deployment.test.mjs');assert.equal(pkg.scripts.smoke,'node scripts/smoke-deployment.mjs');assert.equal(pkg.dependencies['google-auth-library'],undefined);assert.equal(pkg.dependencies['@vercel/blob'],'2.8.0');assert.match(read('scripts/assets.mjs'),/lookup-domain\.js/);assert.match(read('reporting/core.py'),new RegExp(`VERSION = '${pkg.version}'`));});
test('Smoke de autenticação acompanha a versão do package e limita tempo de rede',()=>{const smoke=read('scripts/smoke-auth.mjs');assert.match(smoke,/readFileSync\(new URL\('\.\.\/package\.json'/);assert.match(smoke,/version===expectedVersion/);assert.match(smoke,/AbortSignal\.timeout\(10000\)/);assert.doesNotMatch(smoke,/version===['"]\d+\.\d+\.\d+/);});

test('OCR de imagem usa OpenCV headless no servidor',()=>{const py=read('pyproject.toml');assert.match(py,/rapidocr==3\.9\.2/);assert.match(py,/onnxruntime==1\.30\.0/);assert.match(py,/opencv-python-headless==5\.0\.0\.93/);assert.doesNotMatch(py,/dependencies\s*=\s*\[[^\]]*"opencv-python==/s);assert.match(read('reporting/pdf_ocr.py'),/from rapidocr import RapidOCR/);});

test('Extrato usa Blob privado sem expor token ao navegador',()=>{assert.match(read('src/blob-documents.ts'),/access: 'private'/);assert.match(read('src/blob-documents.ts'),/issueSignedToken/);assert.match(read('api/simples.py'),/simplesDocuments/);assert.match(read('.env.example'),/BLOB_READ_WRITE_TOKEN=/);assert.doesNotMatch(read('public/simulator-ui.js'),/BLOB_READ_WRITE_TOKEN/);});
