import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { database, collection, scope, closeDatabase } from '../src/store.ts';
import { resetLookupIndexes } from '../src/lookup-db.ts';
import { importCatalog } from '../src/lookup-catalog.ts';
import { createGeneration, getGeneration, generationHistory, attachGenerationPurchase, withGeneration } from '../src/generation-store.ts';
import { uploadLookup, finalizeLookup, cancelLookup, processLookup } from '../src/lookup-jobs.ts';
import { purchaseSummary, purchaseHistory } from '../src/purchase-store.ts';
import { routeV4 } from '../src/lookup-http.ts';

test('MongoDB gerações: empresas, retomada, concorrência, conclusão conjunta e isolamento', {skip: !process.env.MONGODB_URI, timeout: 120000}, async () => {
  const oldDb = process.env.MONGODB_DB, oldWs = process.env.WORKSPACE_ID;
  process.env.MONGODB_DB = 'maximum_generation_test_' + randomUUID().replaceAll('-', '');
  process.env.WORKSPACE_ID = 'generation_test';
  resetLookupIndexes();
  const actor = {_id: 'tester', role: 'admin', name: 'Teste', email: 'test@example.test'};
  const viewer = {...actor, role: 'viewer'};
  const errorCode = (code: string) => (error: any) => error.code === code;
  const row = {document: '12345678900', name: 'Pessoa sintética', quantity: '2', grossCents: 10000, discountCents: 2000,
    accessoryCents: 999, freightCents: 500, abatementCents: 300, totalCents: 8200};
  try {
    const catalog = await importCatalog(actor, [{code: '936', name: 'Empresa A'}, {code: '937', name: 'Empresa B'}, {code: '938', name: 'Empresa C'}]);
    const [first, second, outside] = catalog.items.map((client: any) => client.id);
    const input = {generationId: randomUUID(), clientIds: [first, second]};
    const id = input.generationId;
    await assert.rejects(createGeneration(viewer, input), errorCode('FORBIDDEN'));
    await assert.rejects(createGeneration(actor, {...input, clientIds: []}));
    await assert.rejects(createGeneration(actor, {...input, clientIds: [first, first]}));
    await assert.rejects(createGeneration(actor, {...input, clientIds: [randomUUID()]}));
    await assert.rejects(createGeneration(actor, {...input, clientIds: Array.from({length: 51}, () => randomUUID())}));
    const copies = await Promise.all([createGeneration(actor, input), createGeneration(actor, input)]);
    assert(copies.every(copy => copy._id === id && copy.status === 'MISSING' && copy.missingCount === 2));
    assert.equal(await (await collection('generations')).countDocuments(scope()), 1);
    assert.equal((await createGeneration(actor, {...input, clientIds: [second, first]}))._id, id);
    await assert.rejects(createGeneration(actor, {...input, clientIds: [first]}), errorCode('GENERATION_EXISTS'));
    await assert.rejects(createGeneration({...actor, _id: 'other'}, input), errorCode('GENERATION_EXISTS'));
    const attachInput = {clientId: first, importId: randomUUID(), fileName: 'compras-sinteticas.csv', expectedRows: 1};
    await assert.rejects(attachGenerationPurchase(viewer, id, attachInput), errorCode('FORBIDDEN'));
    await assert.rejects(attachGenerationPurchase(actor, id, {...attachInput, clientId: outside}), errorCode('GENERATION_CLIENT'));
    let acquired!: () => void, release!: () => void;
    const locked = new Promise<void>(resolve => { acquired = resolve; });
    const unlock = new Promise<void>(resolve => { release = resolve; });
    const held = withGeneration(id, async () => { acquired(); await unlock; });
    await locked;
    try { await assert.rejects(attachGenerationPurchase(actor, id, attachInput), errorCode('GENERATION_BUSY')); }
    finally { release(); await held; }
    const attached = await attachGenerationPurchase(actor, id, attachInput);
    assert.equal(attached.job.generationId, id);
    assert.equal(attached.generation.inProgressCount, 1);
    assert.equal(attached.generation.missingCount, 1);
    assert.equal(attached.generation.completedCount, 0);
    assert.equal(attached.generation.status, 'MISSING');
    const repeated = await attachGenerationPurchase(actor, id, attachInput);
    assert.equal(repeated.job._id, attached.job._id);
    assert.deepEqual(repeated.generation.companies[0].purchaseJobIds, [attached.job._id]);
    await assert.rejects(attachGenerationPurchase(actor, id, {...attachInput, expectedRows: 2}));
    const colleague = {...actor, _id: 'colleague', role: 'operator'};
    assert.equal((await attachGenerationPurchase(colleague, id, attachInput)).job._id, attached.job._id);
    await assert.rejects(attachGenerationPurchase(colleague, id, {...attachInput, fileName: 'outro.csv'}), errorCode('GENERATION_PURCHASE_EXISTS'));
    await assert.rejects(attachGenerationPurchase(colleague, id, {...attachInput, expectedRows: 2}), errorCode('GENERATION_PURCHASE_EXISTS'));
    await assert.rejects(attachGenerationPurchase(actor, id, {...attachInput, importId: randomUUID()}), errorCode('GENERATION_PURCHASE_EXISTS'));
    const another = await createGeneration(actor, {generationId: randomUUID(), clientIds: [first]});
    await assert.rejects(attachGenerationPurchase(actor, another._id, attachInput), errorCode('GENERATION_PURCHASE_EXISTS'));
    assert.equal((await getGeneration(another._id)).missingCount, 1);
    await uploadLookup(colleague, attached.job._id, {offset: 0, rows: [row]});
    await finalizeLookup(colleague, attached.job._id);
    assert.equal((await purchaseSummary(attached.job._id)).totals.totalCents, 8200);
    const partial = await getGeneration(id);
    assert.equal(partial.status, 'MISSING');
    assert.equal(partial.completedCount, 1);
    assert.equal(partial.companies[0].purchase.status, 'COMPLETED');
    await assert.rejects(attachGenerationPurchase(actor, id, {...attachInput, importId: randomUUID()}), errorCode('GENERATION_PURCHASE_EXISTS'));
    const secondInput = {...attachInput, clientId: second, importId: randomUUID()};
    const cancelled = await attachGenerationPurchase(actor, id, secondInput);
    await cancelLookup(actor, cancelled.job._id);
    assert.equal((await getGeneration(id)).missingCount, 1);
    const replacement = await attachGenerationPurchase(actor, id, {...secondInput, importId: randomUUID()});
    assert.deepEqual(replacement.generation.companies[1].purchaseJobIds, [cancelled.job._id, replacement.job._id]);
    assert.equal(replacement.generation.status, 'IN_PROGRESS');
    await assert.rejects(attachGenerationPurchase(actor, id, secondInput), errorCode('GENERATION_PURCHASE_EXISTS'));
    await uploadLookup(actor, replacement.job._id, {offset: 0, rows: [{...row, document: '00000000000191'}]});
    await finalizeLookup(actor, replacement.job._id);
    await (await collection('providerControl')).deleteMany({});
    await processLookup(actor, replacement.job._id, (async () => new Response('', {status: 404})) as typeof fetch);
    const complete = await getGeneration(id);
    assert.equal(complete.status, 'COMPLETED');
    assert.equal(complete.completedCount, 2);
    assert.equal(complete.missingCount, 0);
    assert.equal(complete.salesAvailable, false);
    assert.equal(complete.companies[1].purchase.generationId, id);
    assert.equal((await purchaseHistory(second, 1)).total, 2);
    const metrics = (await routeV4(actor, 'GET', new URL('https://test/api/v4/dashboard'), {}) as any).metrics;
    assert.equal(metrics.total, 1);
    assert.equal(metrics.unknown, 1);
    assert.equal(metrics.nonOptants, 0);
    assert.equal(metrics.reportingNonOptants, 1);
    assert.equal(metrics.reportingNonOptantsPercent, 100);
    assert.equal(metrics.coverage, 0);
    const visible = await routeV4(viewer, 'GET', new URL('https://test/api/v4/generations/' + id), {}) as any;
    assert.equal(visible._id, id);
    assert.equal(visible.leaseOwner, undefined);
    assert.equal(visible.workspaceId, undefined);
    await assert.rejects(routeV4(actor, 'POST', new URL('https://test/api/v4/generations/' + id + '/sales'), {}), errorCode('SALES_UNAVAILABLE'));
    await assert.rejects(routeV4(actor, 'POST', new URL('https://test/api/v4/generations/' + id + '/purchases'), {...attachInput, type: 'SALES'}), errorCode('SALES_UNAVAILABLE'));
    const oldClientId = complete.companies[0].clientId;
    await (await collection('lookupJobs')).updateOne(scope({_id: attached.job._id}), {$set: {clientId: outside}});
    await assert.rejects(getGeneration(id), errorCode('GENERATION_INCONSISTENT'));
    await (await collection('lookupJobs')).updateOne(scope({_id: attached.job._id}), {$set: {clientId: oldClientId}});
    const history = await generationHistory(1);
    assert.equal(history.total, 2);
    assert.equal(history.items.length, 2);
    assert.equal(history.pageSize, 20);
    assert.equal((await generationHistory(2)).items.length, 0);
    process.env.WORKSPACE_ID = 'another_workspace';
    await assert.rejects(getGeneration(id), errorCode('NOT_FOUND'));
    await assert.rejects(attachGenerationPurchase(actor, id, attachInput), errorCode('NOT_FOUND'));
    assert.equal((await generationHistory(1)).total, 0);
    await assert.rejects(createGeneration(actor, {generationId: randomUUID(), clientIds: [first]}));
    process.env.WORKSPACE_ID = 'generation_test';
    assert.equal(await (await collection('clients')).countDocuments(scope()), 3);
    assert.equal((await (await collection('lookupJobs')).findOne(scope({_id: cancelled.job._id})))?.status, 'CANCELLED');
  } finally {
    await (await database()).dropDatabase();
    await closeDatabase();
    resetLookupIndexes();
    if (oldDb === undefined) delete process.env.MONGODB_DB; else process.env.MONGODB_DB = oldDb;
    if (oldWs === undefined) delete process.env.WORKSPACE_ID; else process.env.WORKSPACE_ID = oldWs;
  }
});
